"""initial

Revision ID: 902cabc5c402
Revises: 
Create Date: 2026-06-15 20:20:11.267654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '902cabc5c402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(length=255), nullable=False),
    sa.Column('weapon', sa.String(length=100), nullable=True),
    sa.Column('skin_name', sa.String(length=200), nullable=True),
    sa.Column('exterior', sa.String(length=50), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=False),
    sa.Column('souvenir', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_hash_name')
    )
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'marketplace_id', 'recorded_at', name='uq_price_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_records')
    op.drop_table('marketplaces')
    op.drop_table('items')
    # ### end Alembic commands ###
